# =============================================================================
# DevOps App Helm Chart - values.yaml
# =============================================================================

# -----------------------------------------------------------------------------
# Namespaces
# -----------------------------------------------------------------------------
namespaces:
  frontend: frontend-ns
  backend: backend-ns
  db: db-ns
# -----------------------------------------------------------------------------
# Frontend Configuration
# -----------------------------------------------------------------------------
frontend:
  replicaCount: 2
  image:
    repository: mahmoudsallem/frontend
    tag: 21e44c8c45de871578a7b82c864e8e335848e3f4
    pullPolicy: Always
  service:
    port: 80
  ingress:
    enabled: true
    ingressClassName: nginx
    host: a01d06f1032a4460e9954daf94e0dac2-1374708381.us-east-1.elb.amazonaws.com
    path: /
# -----------------------------------------------------------------------------
# Backend Configuration
# -----------------------------------------------------------------------------
backend:
  replicaCount: 1
  image:
    repository: mahmoudsallem/backend
    tag: 21e44c8c45de871578a7b82c864e8e335848e3f4
    pullPolicy: IfNotPresent
  service:
    port: 5000
  ingress:
    enabled: true
    host: backend.nti.com
    ingressClassName: nginx
  # ConfigMap values
  config:
    redisPort: "6379"
    postgresPort: "5432"
    postgresDb: appdb
# -----------------------------------------------------------------------------
# Database Configuration
# -----------------------------------------------------------------------------
database:
  postgres:
    replicaCount: 1
    image:
      repository: postgres
      tag: 15-alpine
    port: 5432
    db: appdb
    user: appuser
    password: apppass
  redis:
    replicaCount: 1
    image:
      repository: redis
      tag: 7-alpine
    port: 6379
    password: redispass
# -----------------------------------------------------------------------------
# Network Policies
# -----------------------------------------------------------------------------
networkPolicies:
  enabled: true
  ingressNamespace: ingress-nginx
